services:
  dune-discord-bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
